apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: purl

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - clickhouse.yaml
  - purl.yaml
  - vector-daemonset.yaml

commonLabels:
  app.kubernetes.io/part-of: purl
  app.kubernetes.io/managed-by: kubectl
